'use client'

// PrintableReport — dedicated A4 print document for the Reports page.
//
// Root fix for the PDF export bug: instead of printing the live page (where the
// report preview was hidden with .no-print and Tailwind v4 oklch colors/fonts
// broke), this component renders a clean, complete print document inside a
// `.print-root` portal attached to <body>. The print CSS in globals.css hides
// the entire app and prints ONLY this document.
//
// - Official header: logo, brand, report title, project, period, generated info
// - FULL data (no 50-row truncation) with repeating <thead> on page breaks
// - Totals rows for numeric tables
// - Print-safe explicit sRGB colors (no oklch dependence)

import { useAppStore } from '@/lib/store'
import {
  reportTypes, reportStatusLabels, incidentLabels, handoverStatusLabels,
  equipmentStatusLabels, costCategoryLabels, localized, fmtNum,
} from '@/lib/report-labels'

interface PrintableData {
  type: string
  data: any
  project?: any
  fromDate: string
  toDate: string
}

export function PrintableReport({ data, generatedBy }: { data: PrintableData; generatedBy?: string | null }) {
  const language = useAppStore((s) => s.language)
  const isRtl = language === 'ar'
  const d = data.data || {}
  const reports = d.reports || []
  const cur = isRtl ? 'ر.ع' : 'OMR'
  const dfmt = (v: any) => new Date(v).toLocaleDateString(isRtl ? 'ar-EG' : 'en-US')
  const reportType = reportTypes.find(r => r.id === data.type)

  const totalMeters = reports.reduce((s: number, r: any) => s + (Number(r.dailyMeters) || 0), 0)
  const totalRevenue = reports.reduce((s: number, r: any) => s + (Number(r.dailyRevenue) || 0), 0)

  return (
    <div className="pr-doc" dir={isRtl ? 'rtl' : 'ltr'}>
      {/* ─── Official header ─── */}
      <div className="pr-head">
        <img src="/logo.png" alt="AXIS" className="pr-logo" />
        <div style={{ flex: 1 }}>
          <div className="pr-brand">AXIS</div>
          <div className="pr-sub">{isRtl ? 'أنظمة دفع الأنابيب والأنفاق الدقيقة' : 'Pipe Jacking & Microtunneling Systems'}</div>
        </div>
        <div className="pr-head-badge">{isRtl ? 'تقرير رسمي' : 'Official Report'}</div>
      </div>

      <h1 className="pr-title">{isRtl ? reportType?.labelAr : reportType?.labelEn}</h1>

      {/* ─── Meta block ─── */}
      <table className="pr-meta">
        <tbody>
          <tr>
            <td className="k">{isRtl ? 'المشروع' : 'Project'}</td>
            <td>{data.project ? data.project.name : (isRtl ? 'كل المشاريع' : 'All Projects')}</td>
            <td className="k">{isRtl ? 'الفترة' : 'Period'}</td>
            <td>{data.fromDate} ← {data.toDate}</td>
          </tr>
          <tr>
            <td className="k">{isRtl ? 'تاريخ التوليد' : 'Generated at'}</td>
            <td>{new Date().toLocaleString(isRtl ? 'ar-EG' : 'en-US')}</td>
            <td className="k">{isRtl ? 'مُعد التقرير' : 'Generated by'}</td>
            <td>{generatedBy || '-'}</td>
          </tr>
        </tbody>
      </table>

      {/* ─── Body per report type ─── */}
      {(data.type === 'daily_site' || data.type === 'production') && (
        <>
          <div className="pr-section-title">{isRtl ? `سجل التقارير (${reports.length})` : `Reports Log (${reports.length})`}</div>
          <table className="pr-table">
            <thead>
              <tr>
                <th>{isRtl ? 'التاريخ' : 'Date'}</th>
                <th>{isRtl ? 'المشروع' : 'Project'}</th>
                <th>{isRtl ? 'الخط' : 'Line'}</th>
                <th>{isRtl ? 'أمتار' : 'Meters'}</th>
                <th>{isRtl ? 'العمال' : 'Workers'}</th>
                <th>{isRtl ? 'الحالة' : 'Status'}</th>
              </tr>
            </thead>
            <tbody>
              {reports.map((r: any) => (
                <tr key={r.id}>
                  <td style={{ whiteSpace: 'nowrap' }}>{dfmt(r.reportDate)}</td>
                  <td>{r.project?.name || '-'}</td>
                  <td>{r.driveLine?.lineNumber || '-'}</td>
                  <td className="pr-num">{fmtNum(r.dailyMeters)}</td>
                  <td className="pr-num">{r.workersCount ?? 0}</td>
                  <td>{localized(reportStatusLabels, r.status, isRtl)}</td>
                </tr>
              ))}
              {reports.length === 0 && <tr><td colSpan={6} className="pr-empty">{isRtl ? 'لا توجد تقارير في هذه الفترة' : 'No reports in this period'}</td></tr>}
            </tbody>
            {reports.length > 0 && (
              <tfoot>
                <tr>
                  <td colSpan={3}>{isRtl ? 'الإجمالي' : 'Total'}</td>
                  <td className="pr-num">{fmtNum(totalMeters)}</td>
                  <td className="pr-num">{fmtNum(reports.reduce((s: number, r: any) => s + (Number(r.workersCount) || 0), 0))}</td>
                  <td></td>
                </tr>
              </tfoot>
            )}
          </table>
        </>
      )}

      {data.type === 'attendance' && (
        <>
          <div className="pr-section-title">{isRtl ? `سجل الحضور والغياب (${reports.length})` : `Attendance Log (${reports.length})`}</div>
          <table className="pr-table">
            <thead>
              <tr>
                <th>{isRtl ? 'التاريخ' : 'Date'}</th>
                <th>{isRtl ? 'المشروع' : 'Project'}</th>
                <th>{isRtl ? 'عدد العمال' : 'Workers'}</th>
                <th>{isRtl ? 'الغائبون' : 'Absentees'}</th>
                <th>{isRtl ? 'ملاحظات' : 'Notes'}</th>
              </tr>
            </thead>
            <tbody>
              {reports.map((r: any) => (
                <tr key={r.id}>
                  <td style={{ whiteSpace: 'nowrap' }}>{dfmt(r.reportDate)}</td>
                  <td>{r.project?.name || '-'}</td>
                  <td className="pr-num">{r.workersCount ?? 0}</td>
                  <td>{r.absentees || '-'}</td>
                  <td>{r.attendanceNotes || '-'}</td>
                </tr>
              ))}
              {reports.length === 0 && <tr><td colSpan={5} className="pr-empty">{isRtl ? 'لا توجد سجلات حضور في هذه الفترة' : 'No attendance records in this period'}</td></tr>}
            </tbody>
            {reports.length > 0 && (
              <tfoot>
                <tr>
                  <td colSpan={2}>{isRtl ? 'إجمالي العمالة' : 'Total Workers'}</td>
                  <td className="pr-num">{fmtNum(reports.reduce((s: number, r: any) => s + (Number(r.workersCount) || 0), 0))}</td>
                  <td colSpan={2}></td>
                </tr>
              </tfoot>
            )}
          </table>
        </>
      )}

      {data.type === 'safety' && (
        <>
          <div className="pr-section-title">{isRtl ? `تقارير السلامة (${reports.filter((r: any) => r.safety).length})` : `Safety Reports (${reports.filter((r: any) => r.safety).length})`}</div>
          <table className="pr-table">
            <thead>
              <tr>
                <th>{isRtl ? 'التاريخ' : 'Date'}</th>
                <th>{isRtl ? 'المشروع' : 'Project'}</th>
                <th>{isRtl ? 'المخالفات' : 'Violations'}</th>
                <th>{isRtl ? 'الحوادث' : 'Incidents'}</th>
                <th>{isRtl ? 'موقّع من' : 'Signed by'}</th>
              </tr>
            </thead>
            <tbody>
              {reports.filter((r: any) => r.safety).map((r: any) => (
                <tr key={r.id}>
                  <td style={{ whiteSpace: 'nowrap' }}>{dfmt(r.reportDate)}</td>
                  <td>{r.project?.name || '-'}</td>
                  <td>{r.safety.violations || '-'}</td>
                  <td>{localized(incidentLabels, r.safety.incidentType, isRtl)}</td>
                  <td>{r.safety.signedBy || '-'}</td>
                </tr>
              ))}
              {reports.filter((r: any) => r.safety).length === 0 && <tr><td colSpan={5} className="pr-empty">{isRtl ? 'لا توجد تقارير سلامة في هذه الفترة' : 'No safety reports in this period'}</td></tr>}
            </tbody>
          </table>
        </>
      )}

      {data.type === 'revenue' && (
        <>
          <div className="pr-section-title">{isRtl ? `سجل الإيرادات (${reports.length})` : `Revenue Log (${reports.length})`}</div>
          <p className="pr-note">{isRtl ? 'يُحسب الإيراد من التقارير المعتمدة فقط (الأمتار المحفورة × سعر المتر)' : 'Revenue is calculated from approved reports only (meters × price per meter)'}</p>
          <table className="pr-table">
            <thead>
              <tr>
                <th>{isRtl ? 'التاريخ' : 'Date'}</th>
                <th>{isRtl ? 'المشروع' : 'Project'}</th>
                <th>{isRtl ? 'أمتار اليوم' : 'Daily Meters'}</th>
                <th>{isRtl ? 'الإيراد' : 'Revenue'} ({cur})</th>
              </tr>
            </thead>
            <tbody>
              {reports.map((r: any) => (
                <tr key={r.id}>
                  <td style={{ whiteSpace: 'nowrap' }}>{dfmt(r.reportDate)}</td>
                  <td>{r.project?.name || '-'}</td>
                  <td className="pr-num">{fmtNum(r.dailyMeters)}</td>
                  <td className="pr-num">{fmtNum(r.dailyRevenue)}</td>
                </tr>
              ))}
              {reports.length === 0 && <tr><td colSpan={4} className="pr-empty">{isRtl ? 'لا توجد بيانات إيراد في هذه الفترة' : 'No revenue data in this period'}</td></tr>}
            </tbody>
            {reports.length > 0 && (
              <tfoot>
                <tr>
                  <td colSpan={2}>{isRtl ? 'الإجمالي' : 'Total'}</td>
                  <td className="pr-num">{fmtNum(totalMeters)}</td>
                  <td className="pr-num">{fmtNum(totalRevenue)}</td>
                </tr>
              </tfoot>
            )}
          </table>
        </>
      )}

      {data.type === 'costs' && (() => {
        const costs = d.costs || []
        const rentals = d.rentalAssets || []
        const groups = new Map<string, any[]>()
        for (const c of costs) {
          const key = String(c.category || 'other')
          if (!groups.has(key)) groups.set(key, [])
          groups.get(key)!.push(c)
        }
        const groupList = Array.from(groups.entries()).sort((a, b) =>
          b[1].reduce((s: number, c: any) => s + (Number(c.amount) || 0), 0) -
          a[1].reduce((s: number, c: any) => s + (Number(c.amount) || 0), 0)
        )
        return (
          <>
            <div className="pr-section-title">{isRtl ? 'التكاليف حسب الفئة' : 'Costs by Category'}</div>
            <table className="pr-table">
              <thead>
                <tr>
                  <th>{isRtl ? 'الفئة' : 'Category'}</th>
                  <th style={{ textAlign: 'end' }}>{isRtl ? 'المبلغ' : 'Amount'} ({cur})</th>
                </tr>
              </thead>
              <tbody>
                {(d.byCategory || []).map((c: any, i: number) => (
                  <tr key={i}>
                    <td>{localized(costCategoryLabels, c.category, isRtl)}</td>
                    <td className="pr-num">{fmtNum(c.amount)}</td>
                  </tr>
                ))}
                {(d.byCategory || []).length === 0 && <tr><td colSpan={2} className="pr-empty">{isRtl ? 'لا توجد تكاليف في هذه الفترة' : 'No costs in this period'}</td></tr>}
              </tbody>
              <tfoot>
                <tr><td>{isRtl ? 'إجمالي التكاليف' : 'Total Costs'}</td><td className="pr-num">{fmtNum(d.total)}</td></tr>
                {Number(d.totalRentalCost) > 0 && <tr><td>{isRtl ? 'تكاليف الإيجارات' : 'Rental Costs'}</td><td className="pr-num">{fmtNum(d.totalRentalCost)}</td></tr>}
                <tr><td>{isRtl ? 'الإجمالي الشامل' : 'Grand Total'}</td><td className="pr-num">{fmtNum(d.grandTotal)}</td></tr>
              </tfoot>
            </table>

            {groupList.map(([cat, items]) => {
              const subtotal = items.reduce((s: number, c: any) => s + (Number(c.amount) || 0), 0)
              return (
                <div key={cat} style={{ marginTop: 14 }}>
                  <div className="pr-group-head">
                    <span>{localized(costCategoryLabels, cat, isRtl)} ({items.length})</span>
                    <span>{fmtNum(subtotal)} {cur}</span>
                  </div>
                  <table className="pr-table">
                    <thead>
                      <tr>
                        <th>{isRtl ? 'التاريخ' : 'Date'}</th>
                        <th>{isRtl ? 'البيان' : 'Description'}</th>
                        <th>{isRtl ? 'المشروع' : 'Project'}</th>
                        <th>{isRtl ? 'سجّلها' : 'Recorded by'}</th>
                        <th>{isRtl ? 'ملاحظات' : 'Notes'}</th>
                        <th style={{ textAlign: 'end' }}>{isRtl ? 'المبلغ' : 'Amount'} ({cur})</th>
                      </tr>
                    </thead>
                    <tbody>
                      {items
                        .slice()
                        .sort((a: any, b: any) => new Date(b.date).getTime() - new Date(a.date).getTime())
                        .map((c: any) => (
                        <tr key={c.id}>
                          <td style={{ whiteSpace: 'nowrap' }}>{dfmt(c.date)}</td>
                          <td>{c.description || '-'}</td>
                          <td>{c.project?.name || '-'}</td>
                          <td>{c.recordedBy ? (isRtl ? (c.recordedBy.name || '-') : (c.recordedBy.nameEn || c.recordedBy.name || '-')) : '-'}</td>
                          <td>{c.notes || '-'}</td>
                          <td className="pr-num">{fmtNum(c.amount)}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              )
            })}

            {rentals.length > 0 && (
              <div style={{ marginTop: 14 }}>
                <div className="pr-group-head">
                  <span>{isRtl ? 'الإيجارات الشهرية النشطة (معدات وأصول مستأجرة)' : 'Active Monthly Rentals (rented equipment & assets)'}</span>
                  <span>{fmtNum(d.totalRentalCost)} {cur}</span>
                </div>
                <table className="pr-table">
                  <thead>
                    <tr>
                      <th>{isRtl ? 'المعدة / الأصل' : 'Asset'}</th>
                      <th>{isRtl ? 'المورد' : 'Supplier'}</th>
                      <th>{isRtl ? 'المشروع' : 'Project'}</th>
                      <th style={{ textAlign: 'end' }}>{isRtl ? 'الإيجار الشهري' : 'Monthly Rent'} ({cur})</th>
                    </tr>
                  </thead>
                  <tbody>
                    {rentals.map((a: any) => (
                      <tr key={a.id}>
                        <td>{a.name}</td>
                        <td>{a.supplier || '-'}</td>
                        <td>{a.projectName || '-'}</td>
                        <td className="pr-num">{fmtNum(a.rentalCost)}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </>
        )
      })()}

      {data.type === 'profit' && (
        <>
          <div className="pr-section-title">{isRtl ? 'ملخص الربحية' : 'Profitability Summary'}</div>
          <div className="pr-kv-grid">
            <div className="pr-kv">
              <p className="k">{isRtl ? 'إجمالي الإيراد' : 'Total Revenue'}</p>
              <p className="v" style={{ color: '#047857' }}>{fmtNum(d.totalRevenue)} {cur}</p>
            </div>
            <div className="pr-kv">
              <p className="k">{isRtl ? 'إجمالي التكاليف' : 'Total Costs'}</p>
              <p className="v" style={{ color: '#b91c1c' }}>{fmtNum(d.totalCosts)} {cur}</p>
            </div>
            <div className="pr-kv">
              <p className="k">{isRtl ? 'صافي الربح' : 'Net Profit'}</p>
              <p className="v" style={{ color: (Number(d.netProfit) || 0) >= 0 ? '#047857' : '#b91c1c' }}>{fmtNum(d.netProfit)} {cur}</p>
            </div>
            <div className="pr-kv">
              <p className="k">{isRtl ? 'هامش الربحية' : 'Profit Margin'}</p>
              <p className="v">{Number(d.totalRevenue) > 0 ? ((Number(d.netProfit) / Number(d.totalRevenue)) * 100).toFixed(1) : '0.0'}%</p>
            </div>
          </div>
          {(d.byCategory || []).length > 0 && (
            <>
              <div className="pr-section-title">{isRtl ? 'تفصيل التكاليف حسب الفئة' : 'Costs Breakdown'}</div>
              <table className="pr-table">
                <thead>
                  <tr>
                    <th>{isRtl ? 'الفئة' : 'Category'}</th>
                    <th style={{ textAlign: 'end' }}>{isRtl ? 'المبلغ' : 'Amount'} ({cur})</th>
                  </tr>
                </thead>
                <tbody>
                  {d.byCategory.map((c: any, i: number) => (
                    <tr key={i}>
                      <td>{localized(costCategoryLabels, c.category, isRtl)}</td>
                      <td className="pr-num">{fmtNum(c.amount)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </>
          )}
        </>
      )}

      {data.type === 'equipment' && (
        <>
          <div className="pr-section-title">{isRtl ? `قائمة المعدات (${(d.equipment || []).length})` : `Equipment List (${(d.equipment || []).length})`}</div>
          <table className="pr-table">
            <thead>
              <tr>
                <th>{isRtl ? 'المعدة' : 'Equipment'}</th>
                <th>{isRtl ? 'الرقم' : 'Number'}</th>
                <th>{isRtl ? 'الحالة' : 'Status'}</th>
              </tr>
            </thead>
            <tbody>
              {(d.equipment || []).map((eq: any) => (
                <tr key={eq.id}>
                  <td>{eq.name}</td>
                  <td style={{ fontFamily: 'monospace' }}>{eq.number}</td>
                  <td>{localized(equipmentStatusLabels, eq.status, isRtl)}</td>
                </tr>
              ))}
              {(d.equipment || []).length === 0 && <tr><td colSpan={3} className="pr-empty">{isRtl ? 'لا توجد معدات' : 'No equipment'}</td></tr>}
            </tbody>
          </table>
        </>
      )}

      {(data.type === 'weekly' || data.type === 'monthly') && (
        <>
          <div className="pr-section-title">{isRtl ? 'ملخص الفترة' : 'Period Summary'}</div>
          <div className="pr-kv-grid">
            <div className="pr-kv">
              <p className="k">{isRtl ? 'أمتار الفترة' : 'Period Meters'}</p>
              <p className="v">{fmtNum(d.totalMeters)}</p>
            </div>
            <div className="pr-kv">
              <p className="k">{isRtl ? 'إيرادات الفترة' : 'Period Revenue'}</p>
              <p className="v" style={{ color: '#047857' }}>{fmtNum(d.totalRevenue)} {cur}</p>
            </div>
            <div className="pr-kv">
              <p className="k">{isRtl ? 'تكاليف الفترة' : 'Period Costs'}</p>
              <p className="v" style={{ color: '#b91c1c' }}>{fmtNum(d.totalCosts)} {cur}</p>
            </div>
            <div className="pr-kv">
              <p className="k">{isRtl ? 'صافي الربح' : 'Net Profit'}</p>
              <p className="v" style={{ color: (Number(d.netProfit) || 0) >= 0 ? '#047857' : '#b91c1c' }}>{fmtNum(d.netProfit)} {cur}</p>
            </div>
          </div>
          <div className="pr-section-title">{isRtl ? 'تقدم المشاريع' : 'Projects Progress'}</div>
          <table className="pr-table">
            <thead>
              <tr>
                <th>{isRtl ? 'المشروع' : 'Project'}</th>
                <th style={{ width: 220 }}>{isRtl ? 'نسبة التقدم' : 'Progress'}</th>
                <th style={{ textAlign: 'end' }}>%</th>
              </tr>
            </thead>
            <tbody>
              {(d.projects || []).map((p: any) => {
                const pct = Math.max(0, Math.min(100, Number(p.progress) || 0))
                return (
                  <tr key={p.id}>
                    <td>{p.name}</td>
                    <td>
                      <div className="pr-bar"><div style={{ width: pct + '%' }} /></div>
                    </td>
                    <td className="pr-num">{pct.toFixed(1)}</td>
                  </tr>
                )
              })}
              {(d.projects || []).length === 0 && <tr><td colSpan={3} className="pr-empty">{isRtl ? 'لا توجد مشاريع' : 'No projects'}</td></tr>}
            </tbody>
          </table>
        </>
      )}

      {data.type === 'handover' && (
        <>
          <div className="pr-section-title">{isRtl ? `سجلات التسليم (${(d.finishings || []).length})` : `Handover Records (${(d.finishings || []).length})`}</div>
          <table className="pr-table">
            <thead>
              <tr>
                <th>{isRtl ? 'المشروع' : 'Project'}</th>
                <th>{isRtl ? 'التاريخ' : 'Date'}</th>
                <th>{isRtl ? 'حالة التسليم' : 'Handover Status'}</th>
                <th>{isRtl ? 'موقّع من' : 'Signed by'}</th>
              </tr>
            </thead>
            <tbody>
              {(d.finishings || []).map((f: any) => (
                <tr key={f.id}>
                  <td>{f.project?.name || '-'}</td>
                  <td style={{ whiteSpace: 'nowrap' }}>{dfmt(f.date)}</td>
                  <td>{localized(handoverStatusLabels, f.handoverStatus, isRtl)}</td>
                  <td>{f.signedBy || '-'}</td>
                </tr>
              ))}
              {(d.finishings || []).length === 0 && <tr><td colSpan={4} className="pr-empty">{isRtl ? 'لا توجد سجلات تسليم في هذه الفترة' : 'No handover records in this period'}</td></tr>}
            </tbody>
          </table>
        </>
      )}

      {/* ─── Footer ─── */}
      <div className="pr-foot">
        <span>AXIS — {isRtl ? 'نظام إدارة عمليات دفع الأنابيب' : 'Pipe Jacking Operations Management'}</span>
        <span>{isRtl ? 'تقرير آلي مولّد من النظام' : 'Auto-generated system report'} — {new Date().toLocaleDateString(isRtl ? 'ar-EG' : 'en-US')}</span>
      </div>
    </div>
  )
}

